config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'home#index'

  get 'players', to: 'players#index'
  post 'challenge', to: 'games#new'

  get 'users_search' => 'users_indices#index'

  resources :games, only: [:index] do
    get 'pending', on: :collection
    post 'send_result', on: :member
    post 'accept_result', on: :member
  end

end

app/models/game.rb
class Game
  include Mongoid::Document
  field :result, type: String
  field :challenger_accepted, type: Boolean, default: false
  field :challenged_accepted, type: Boolean, default: false
  belongs_to :winner, class_name: 'User', optional: true
  belongs_to :challenger, class_name: 'User'
  belongs_to :challenged, class_name: 'User'
  has_and_belongs_to_many :users

  def end_game!
    game = EloRating::Match.new
    users.each do |user|
      game.add_player(rating: user.elo_rating, winner: winner == user)
    end
    new_ratings = game.updated_ratings
    users.each_with_index do |user, i|
      user.update(elo_rating: new_ratings[i])
    end
  end
end

app/models/redis_storage.rb
class RedisStorage
  include Singleton

  def get_players
    users = redis.get('users') || update_players
  end

  def update_players
    p 'redis_update'
    users = User.all.to_json
    redis.set('users', users)
  end

  private

  def redis
    @redis ||= Redis.new(host: 'redis', port: '6379')
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  field :elo_rating, type: Integer, default: 1200

  has_and_belongs_to_many :games


  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!
  def index
    @games = Game.all
  end

  def new
    challenged = User.find_by(email: params[:email])
    if challenged == current_user
      flash[:error] = "Can't challenge yourself"
      redirect_to players_path and return
    end
    game = Game.new
    game.users << current_user
    game.users << challenged
    game.challenger = current_user
    game.challenged = challenged
    game.save
    redirect_to pending_games_path
  end

  def pending
    @pending_result = current_user.games.where(:result => nil)
    @pending_accept = current_user
                        .games
                        .where(:result.ne => nil)
                        .or(
                          {:challenger => current_user, :challenger_accepted => false},
                          {:challenged => current_user, :challenged_accepted => false})
  end

  def send_result
    game = Game.find_by(id: params[:id])
    if game.result
      flash[:error] = 'already has a result'
      redirect_to pending_games_path and return
    end
    game.result = "#{params[:challenger_result]}:#{params[:challenged_result]}"
    game.challenger == current_user ? game.challenger_accepted = true : game.challenged_accepted = true
    game.save
    redirect_to pending_games_path
  end

  def accept_result
    game = Game.find_by(id: params[:id])
    game.challenger == current_user ? game.challenger_accepted = true : game.challenged_accepted = true
    challenger_score, challenged_score = game.result.split(':').map(&:to_i)
    game.winner = challenger_score > challenged_score ? game.challenger : game.challenged
    game.save
    game.end_game!
    askredis('update_players')
    redirect_to games_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = users_from_redis
  end

  private

  def users_from_redis
    users = RedisStorage.instance.get_players
    JSON.load(users)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true
module Users
  class RegistrationsController < Devise::RegistrationsController
    include ApplicationHelper
    def create
      super do |resource|
        askredis('update_players')
      end
    end
  end
end

app/controllers/users_indices_controller.rb
# frozen_string_literal: true
class UsersIndicesController < ApplicationController
  def index
    email = params[:email]
    @search = email
    @users = UsersIndex.query(match: {email: {query: email, fuzziness: 'AUTO'}})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def askredis(msg)
    conn = Bunny.new(host: 'rabbitmq', automatically_recover: false)
    conn.start
    ch   = conn.create_channel
    q    = ch.queue("redis_queue", :durable => true)
    q.publish(msg, :persistent => true)
    puts " [x] Sent #{msg}"
    conn.close
  end
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/views/games/index.slim
p All ended games with the results

- @games.each do |game|
  p="Challenger: #{game.challenger.email} Challenged: #{game.challenged.email} Winner: #{game.winner&.email} Result: #{game.result} Accepted: #{game.challenger_accepted && game.challenged_accepted}"

app/views/games/pending.slim
div.results
  p Pending results:
  - @pending_result.each do |pe|
    hr
    p= "Challenger: #{pe.challenger.email}"
    p= "Challenged: #{pe.challenged.email}"
    = form_tag send_result_game_path(pe), method: :post do
      h3 Challenger score
      = number_field_tag :challenger_result, 0, in: 0..15
      h3 Challenged score
      = number_field_tag :challenged_result, 0, in: 0..15
      h3 Submit
      = submit_tag 'Click'

div.accept
  p Pending accept:
  - @pending_accept.each do |pa|
    hr
    p= "Challenger: #{pa.challenger.email}"
    p= "Challenged: #{pa.challenged.email}"
    p= pa.result
    = form_tag accept_result_game_path(pa), method: :post do
      h3 Submit
      = submit_tag 'Click'

app/views/home/index.slim
p HELLO
- if user_signed_in?
  p "Welcome #{current_user.email}"
  p= link_to "Sign out", destroy_user_session_path, :method => :delete
- else
  p= link_to "Sign in", new_user_session_path
  p= link_to "Sign up", new_user_registration_path

app/views/layouts/_links.slim
p= link_to "All players", players_path
p= link_to "All games ", games_path
=form_tag users_search_path, method: :get do
  = text_field_tag :email
  = submit_tag 'Search fuzzy'

p= link_to 'Games pending ', pending_games_path
p= link_to 'Home', root_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render partial: 'layouts/links' %>
    <%= yield %>
  </body>
</html>

app/views/players/index.slim
- if flash[:error]
  div class="error"
    = flash[:error]

p All players sorted by their rating

- @users.each do |user|
  p #{user['email']} #{user['elo_rating']}
  = link_to 'Challenge', challenge_path(email: user['email']), method: :post

app/views/users_indices/index.slim
- if flash[:error]
  div class="error"
    = flash[:error]

p Users searched by #{@search}

- @users.each do |user|
  p Email: #{user.email} Rating: #{user.elo_rating} Games won: #{user.games_won}
  = link_to 'Challenge', challenge_path(email: user.email), method: :post